// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkahqqgckseudkzfyjij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrYWhxcWdja3NldWRremZ5amlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MjYwMDMsImV4cCI6MjA2MjUwMjAwM30.AqAb6SB6jyRtZ2WwhuYcze2C6Ckdn5-kK3HGYYGGYs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);